name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
      - name: Install dependencies and run application
        run: |
          cd Client/LetsTalk
          npm ci

      - name: Build application
        run: |
          cd Client/LetsTalk
          npm run build --if-present

      - name: Run unit tests
        run: |
          cd Client/LetsTalk
          npm test

      - name: Start server
        run: |
          cd Client/LetsTalk
          npm start &
        env:
          CI: true

      - name: Wait for server to start
        run: sleep 30

      # - name: Run Cypress tests
      #   run: |
      #     cd Client/LetsTalk
      #     npx cypress run